# Generated by Django 4.2.7 on 2025-08-24 03:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyactivity',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='companychecklist',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='companydatasubmission',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='companyframework',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='companyprofileanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='companyactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companychecklist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companydatasubmission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyframework',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companyprofileanswer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='meter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companydatasubmission',
            name='evidence_file',
            field=models.FileField(blank=True, upload_to='evidence/%Y/%m/%d/'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='companyactivity',
            unique_together={('user', 'company', 'activity')},
        ),
        migrations.AlterUniqueTogether(
            name='companychecklist',
            unique_together={('user', 'company', 'element')},
        ),
        migrations.AlterUniqueTogether(
            name='companydatasubmission',
            unique_together={('user', 'company', 'element', 'meter', 'reporting_year', 'reporting_period')},
        ),
        migrations.AlterUniqueTogether(
            name='companyframework',
            unique_together={('user', 'company', 'framework')},
        ),
        migrations.AlterUniqueTogether(
            name='companyprofileanswer',
            unique_together={('user', 'company', 'question')},
        ),
    ]
