# Generated by Django
from django.db import migrations
from django.contrib.auth.models import User

def assign_default_user(apps, schema_editor):
    """Assign existing records to a default user"""
    User = apps.get_model('auth', 'User')
    Company = apps.get_model('core', 'Company')
    CompanyActivity = apps.get_model('core', 'CompanyActivity')
    CompanyFramework = apps.get_model('core', 'CompanyFramework')
    CompanyProfileAnswer = apps.get_model('core', 'CompanyProfileAnswer')
    Meter = apps.get_model('core', 'Meter')
    CompanyDataSubmission = apps.get_model('core', 'CompanyDataSubmission')
    CompanyChecklist = apps.get_model('core', 'CompanyChecklist')
    Activity = apps.get_model('core', 'Activity')
    
    # Get or create default user
    try:
        default_user = User.objects.get(username='admin')
    except User.DoesNotExist:
        default_user = User.objects.create_user(
            username='admin',
            email='admin@example.com',
            password='admin123'  # Change this in production
        )
    
    # Assign all existing records to default user
    Company.objects.filter(user__isnull=True).update(user=default_user)
    CompanyActivity.objects.filter(user__isnull=True).update(user=default_user)
    CompanyFramework.objects.filter(user__isnull=True).update(user=default_user)
    CompanyProfileAnswer.objects.filter(user__isnull=True).update(user=default_user)
    Meter.objects.filter(user__isnull=True).update(user=default_user)
    CompanyDataSubmission.objects.filter(user__isnull=True).update(user=default_user)
    CompanyChecklist.objects.filter(user__isnull=True).update(user=default_user)
    Activity.objects.filter(created_by__isnull=True, is_custom=True).update(created_by=default_user)

def reverse_assign_default_user(apps, schema_editor):
    """Reverse the assignment (not really needed but good practice)"""
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_user_fields_to_models'),
    ]

    operations = [
        migrations.RunPython(assign_default_user, reverse_assign_default_user),
    ]