# Generated by Django 4.2.7 on 2025-08-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_assign_existing_data_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='is_auto_created',
            field=models.BooleanField(default=False),
        ),
    ]
