# Generated by Django 4.2.7 on 2025-08-26 06:18

from django.db import migrations, models


def assign_unique_company_codes(apps, schema_editor):
    """Assign unique company codes to existing companies"""
    Company = apps.get_model('core', 'Company')
    
    companies = Company.objects.all()
    emirate_counters = {}
    
    for company in companies:
        emirate = company.emirate
        if emirate not in emirate_counters:
            emirate_counters[emirate] = 1
        
        # Create code based on emirate
        emirate_code_map = {
            'dubai': 'DXB',
            'abu_dhabi': 'AUH',
            'sharjah': 'SHJ',
            'ajman': 'AJM',
            'umm_al_quwain': 'UAQ',
            'ras_al_khaimah': 'RAK',
            'fujairah': 'FJR',
        }
        
        emirate_code = emirate_code_map.get(emirate, 'UAE')
        company_code = f"{emirate_code}{emirate_counters[emirate]:03d}"
        
        company.company_code = company_code
        company.save()
        
        emirate_counters[emirate] += 1


def reverse_company_codes(apps, schema_editor):
    """Reverse operation - set all company codes to default"""
    Company = apps.get_model('core', 'Company')
    Company.objects.update(company_code='TEMP001')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_task_assignment'),
    ]

    operations = [
        # First add the fields without unique constraint
        migrations.AddField(
            model_name='company',
            name='company_code',
            field=models.CharField(default='TEMP001', help_text='Unique company identifier code (e.g., DXB001)', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='temp@example.com', help_text='Required business email address', max_length=254),
        ),
        # Assign unique codes to existing companies
        migrations.RunPython(assign_unique_company_codes, reverse_company_codes),
        # Now add the unique constraint
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(help_text='Unique company identifier code (e.g., DXB001)', max_length=10, unique=True),
        ),
    ]