# Generated by Django 4.2.7 on 2025-08-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_company_company_code_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='must_reset_password',
            field=models.BooleanField(default=False, help_text='User must reset password on next login'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(help_text='Required business email address', max_length=254),
        ),
    ]
