# Generated by Django 4.2.7 on 2025-09-03 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_userprofile_email_verified_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='verification_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
