# Generated by Django 4.2.7 on 2025-09-04 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_elementassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='elementassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='elementassignment',
            name='assignment_level',
            field=models.CharField(choices=[('element', 'Individual Element'), ('category', 'Category Level')], default='element', max_length=20),
        ),
        migrations.AddField(
            model_name='elementassignment',
            name='category',
            field=models.CharField(blank=True, choices=[('Environmental', 'Environmental'), ('Social', 'Social'), ('Governance', 'Governance')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='elementassignment',
            name='checklist_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.companychecklist'),
        ),
    ]
