# Generated by Django 4.2.7 on 2025-09-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_elementassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataelement',
            name='category',
            field=models.CharField(choices=[('Environmental', 'Environmental'), ('Social', 'Social'), ('Governance', 'Governance')], default='Environmental', max_length=50),
        ),
    ]
