# Generated by Django 4.2.7 on 2025-09-07 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_category_to_dataelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='simplelogin_alias',
            field=models.EmailField(blank=True, help_text='SimpleLogin alias for privacy protection', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='simplelogin_alias_id',
            field=models.CharField(blank=True, help_text='SimpleLogin alias ID from API', max_length=100, null=True),
        ),
    ]
