# Generated by Django 4.2.7 on 2025-09-10 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_simplelogin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='core.site'),
        ),
    ]
