# Generated by Django 4.2.7 on 2025-09-10 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0017_add_site_to_meter'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companychecklist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companychecklist',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='core.site'),
        ),
        migrations.AlterUniqueTogether(
            name='companychecklist',
            unique_together={('user', 'company', 'site', 'element')},
        ),
    ]
