# Generated by Django 4.2.7 on 2025-09-10 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0018_add_site_to_checklist'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companyprofileanswer',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companyprofileanswer',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_answers', to='core.site'),
        ),
        migrations.AlterUniqueTogether(
            name='companyprofileanswer',
            unique_together={('user', 'company', 'site', 'question')},
        ),
    ]
