# Generated by Django 4.2.7 on 2025-09-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_add_site_to_profile_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='view_all_locations',
            field=models.BooleanField(default=False, help_text='User is viewing all locations instead of a specific site'),
        ),
    ]
