# Generated by Django 4.2.7 on 2025-09-13 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_userprofile_view_all_locations'),
    ]

    operations = [
    ]
