# Generated by Django 4.2.7 on 2025-09-13 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0022_usersiteassignment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companydatasubmission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='companydatasubmission',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_submissions', to='core.site'),
        ),
        migrations.AlterUniqueTogether(
            name='companydatasubmission',
            unique_together={('user', 'company', 'site', 'element', 'meter', 'reporting_year', 'reporting_period')},
        ),
    ]
