# Generated by Django 4.2.7 on 2025-09-15 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_frameworkelement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companychecklist',
            name='frameworks',
        ),
        migrations.AddField(
            model_name='companychecklist',
            name='framework_id',
            field=models.CharField(default='UAE-CLIMATE-LAW-2024', max_length=100),
        ),
        migrations.AlterField(
            model_name='companychecklist',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.frameworkelement'),
        ),
    ]
