# Generated by Django 4.2.7 on 2025-09-15 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_update_companychecklist_to_frameworkelement'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydatasubmission',
            name='framework_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.frameworkelement'),
        ),
        migrations.AlterField(
            model_name='companydatasubmission',
            name='element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.dataelement'),
        ),
    ]
